### ISSUE TITLE
Packaging of asciinema 2.1.0

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema#116]
Opening this issue to discuss the best way for package maintainers to be notified about new asciinema releases.

We could create a mailing list for this, or use https://github.com/asciinema/asciinema/releases.atom like @jakubjedelsky suggested (https://github.com/asciinema/asciinema/issues/43#issuecomment-117053123). Alternatively I could be reopening this issue and pinging you here in the comments whenever new release is out. Any other ideas and/or preferences?

/cc @jakubjedelsky @zanchey @Dr-Terrible @larryv

UPDATE: So I just keep this issue open and comment when there's new release. Package maintainers can subscribe to this issue to get notified.

**Comment by zanchey** [comment]
The atom feed is enough for me. SourceForge used to be the place for mailing lists, but I think they've gone a bit evil now. We have a mailman server if you want to use that.

**Comment by Dr-Terrible** [comment]
The atom feed is enough for me too.
If by any chance I miss a release and users are complaining, feel free to poke me via GitHub's issues through my Gentoo overlay.

**Comment by swills** [comment]
Personally, I'd prefer an email of some kind, either mailing list or github issue email, either is fine. Thanks!

**Comment by larryv** [comment]
I'd also prefer email notifications (to minimize update lag), but I'd be fine with the atom feed.

**Comment by sickill** [comment]
I have just released 1.2.0 /cc @larryv @swills @Dr-Terrible @zanchey @jakubjedelsky

**Comment by Dr-Terrible** [comment]
@sickill Done! Thank you for the reminder.

v1.2.0 tested with both Go1.4.x and Go1.5.x (Gentoo/Linux x86-64), and everything works as expected, with all the unit tests passing. Ebuild just pushed in my overlay: Dr-Terrible/go-overlay@485968240b2f646c675b0630f452d28e99ca41cc.

**Comment by sickill** [comment]
@Dr-Terrible wow, that was quick! Thanks!

**Comment by sickill** [comment]
@youtux thanks for updating Homebrew package!

**Comment by youtux** [comment]
@sickill you are welcome. Also, I use [sibbell.com](sibbel.com) to get updates via email every time a starred github project gets a new tag.

**Comment by zanchey** [comment]
I've updated the Ubuntu packages; sorry for the delay.

**Comment by sickill** [comment]
@zanchey thanks!

**Comment by larryv** [comment]
[updated in MacPorts](https://trac.macports.org/changeset/148664/), only 3 months late 😓

**Comment by sickill** [comment]
@larryv no prob, thanks!

**Comment by sickill** [comment]
We have a new release! This new 1.3 version is back on Python (read more about it here: http://blog.asciinema.org/post/and-now-for-something-completely-different/). Sorry if this adds you more work (switching build toolchain from Go to Python)! But I believe in the long run the packaging will be simpler, especially that as of this version we have *zero external dependencies* 💥

**Comment by Dr-Terrible** [comment]
Sorry @sickill, I can't add a python package to my go overlay, so I'm forced to remove asciinema. Or at least, I'll keep and maintain the previous Golang implementations, but not the new ones in python (there are too many dependencies to wrangle).

**Comment by sickill** [comment]
@Dr-Terrible ok. Maybe original portage package maintainers will be able to update the 0.9.8 ebuild to 1.3.0. Thanks!

**Comment by larryv** [comment]
[Updated in MacPorts](https://trac.macports.org/changeset/150314). As you can see from that diff, switching back to Python made things rather easier for me. Thank you! 😄

**Comment by Dr-Terrible** [comment]
@sickill I think so, but at the moment there is no maintainer for the ebuild, so it will take some time before asciinema will be properly added to the Portage tree. To speed up the process a little, I think I'm going to submit a proper ebuild (at least for v1.3.0) in the next days, if I'm not too busy doing other stuff.

**Comment by jakubjedelsky** [comment]
Love the change to python3, it's much more better to package it for me. Builds for Fedora 24,23 and EPEL 7 are prepared and will go to testing repos soon.

**Comment by zanchey** [comment]
Done in the Ubuntu PPA. Likewise, the packaging is significantly smaller now.

**Comment by gfa** [comment]
i'm the maintainer for debian, I've recently subscribed to the blog, i'll subscribe to the releases atom feed.
I prefer email but i run a rss-> email gateway so is the same for me

working on the 1.3.0 package, just a week latter i finished to work on go package, please don't switch language implementations again

**Comment by sickill** [comment]
@gfa thanks for your work Gustavo. No worries, we are staying with Python for good.

**Comment by swills** [comment]
Finally updated to 1.3.0 in FreeBSD ports. Thanks for the heads up.

**Comment by sickill** [comment]
@swills awesome, thanks!

**Comment by sickill** [comment]
Hey there good people! We have a new release, 1.4.0 - https://pypi.python.org/pypi/asciinema/1.4.0

**Comment by jakubjedelsky** [comment]
@sickill cool, update is going to Fedora and EPEL 7 testing repos right now. It should be in stable in 7 (fedora) or 14 (epel) days.

**Comment by zanchey** [comment]
Uploaded, new builds pending - sorry for the wait!

**Comment by sickill** [comment]
Hey! We have a new release, v2.0.0. 

https://github.com/asciinema/asciinema/releases/tag/v2.0.0
https://pypi.org/project/asciinema/2.0.0/

🎉🎉🎉

**Comment by jakubjedelsky** [comment]
Congrats to v2, @sickill ! 🎉 

I'm a little bit out of focusing to the asciinema development right now. Is the 2.0.0 version backward compatible with older releases (1.4.0)? I would like to push the update to current stables, but not sure if it won't break something.

Thanks!

**Comment by sickill** [comment]
@jakubjedelsky thanks! It uses new file format, so recordings created with this new version can't be played in the terminal with 1.4.0 and older. All recordings (old and new) can be played with 2.0 though, and also web player and asciinema-server have been updated a while ago to support asciicast v2 format.

**Comment by jakubjedelsky** [comment]
@sickill nice! Many thanks for these details 👍

**Comment by swills** [comment]
2.0.0 committed to FreeBSD ports.

**Comment by sickill** [comment]
@swills fantastic, thanks!

**Comment by zanchey** [comment]
I've added Ubuntu packages for the currently released versions.

2.0.0 was already in Bionic, which has a different tarball than the one I downloaded from Github. The upstream packaging can't be backported (requires new debhelper), so I've used the existing packaging with the upstream tarball.

There's been a bit of a delay due to other pressures - sorry. If anyone would like to take over maintaining the Ubuntu PPA, I'm happy to hand it over!

**Comment by gfa** [comment]
@zanchey asciinema is up to date in debian, any reason why is not being imported in ubuntu?

**Comment by zanchey** [comment]
It's up to date in testing and imported into bionic, which as you know are both unreleased, and so the PPA is for people wishing to use a new version of asciinema on an older version of Ubuntu (or Debian).

**Comment by sickill** [comment]
Thank you @zanchey for you work on this!

**Comment by sickill** [comment]
I've just released 2.0.1.

https://pypi.org/project/asciinema/2.0.1/
https://github.com/asciinema/asciinema/releases/tag/v2.0.1

There was a bug in 2.0 in config file handling code, which caused creation of the file at `~/.asciinema/config` instead of `~/.config/asciinema/config`. This releases fixes that.

@zanchey do you think there's a chance for 2.0.1 to be included in final Bionic release? I see final beta freeze is tomorrow 😐

**Comment by zanchey** [comment]
My packages don't get pulled into the official releases, but I'll try and get a 2.0.1 version uploaded today.

**Comment by zanchey** [comment]
Done.

**Comment by sickill** [comment]
@zanchey great, thx!

**Comment by just4t** [comment]
Started today with _asciinema_ ... **First of all, thanks a lot for the tool and service.**
Installed as _snap_ app. in **Linux Mint 19c** desktop and over an **Ubuntu 18.04 LTS** powered cloud server and looks it works perfectly, but ...

- Just noticed the installed version via [snapd app.](https://snapcraft.io/asciinema) is the **1.4** and not a latest **2.0.1+** ... !?

- Have you plans to release the **_asciinema 2.0.1+_** snap app. package soon?

**Comment by sickill** [comment]
@flexiondotorg any chance you could update snap to 2.0.1?

**Comment by sickill** [comment]
I have temporarily removed snap installation option. It doesn't seem anyone is maintaining it anymore.

**Comment by sickill** [comment]
It seems Ubuntu 18.04 has asciinema 2.0.0 (https://packages.ubuntu.com/bionic/asciinema) and 19.04 has 2.0.2 (https://packages.ubuntu.com/disco/asciinema). Any chance you can update your ppa @zanchey to 2.0.2 for those on older Ubuntu and Debian versions?

**Comment by zanchey** [comment]
Done! I ended up reusing my packaging metadata, rather than copying from 19.04, as the debhelper requirements are too high for the backport to work easily.

**Comment by sickill** [comment]
@zanchey great! Thank you 🏆

**Comment by om26er** [comment]
@sickill since I have been the maintainer of the snap package, I think it would make sense to bring back the snap installation instructions, probably elevated as "recommended" for Linux based systems. I had created an issue https://github.com/asciinema/asciinema/issues/382 before I came here.

**Comment by mario23174** [comment]
1

**Comment by aarek-eng** [comment]
Installation via pip didn't work on Windows 10.  Is it an issue with my setup, or do I need to create a venv, or...? Please let me know what information is missing, and I'll try and provide it.

```
PS C:\Users\user\Documents\GitHub\vagrant> pip install asciinema
Collecting asciinema
  Downloading asciinema-2.0.2.tar.gz (35 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-p1stt4vv\\asciinema_6b62e678e99c46198b216b8875ea9855\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-p1stt4vv\\asciinema_6b62e678e99c46198b216b8875ea9855\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-ui2m3wmb'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-p1stt4vv\asciinema_6b62e678e99c46198b216b8875ea9855\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-p1stt4vv\asciinema_6b62e678e99c46198b216b8875ea9855\setup.py", line 1, in <module>
        import asciinema
      File "C:\Users\user\AppData\Local\Temp\pip-install-p1stt4vv\asciinema_6b62e678e99c46198b216b8875ea9855\asciinema\__init__.py", line 15, in <module>
        import asciinema.pty as pty
      File "C:\Users\user\AppData\Local\Temp\pip-install-p1stt4vv\asciinema_6b62e678e99c46198b216b8875ea9855\asciinema\pty.py", line 3, in <module>
        import fcntl
    ModuleNotFoundError: No module named 'fcntl'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a7/71/771c859795e02c71c187546f34f7535487b97425bc1dad1e5f6ad2651357/asciinema-2.0.2.tar.gz#sha256=32f2c1a046564e030708e596f67e0405425d1eca9d5ec83cd917ef8da06bc423 (from https://pypi.org/simple/asciinema/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading asciinema-2.0.1.tar.gz (17 kB)
Building wheels for collected packages: asciinema
  Building wheel for asciinema (setup.py) ... done
  Created wheel for asciinema: filename=asciinema-2.0.1-py3-none-any.whl size=19340 sha256=49c998fc7f48557e13c3e601bab478308f6e05b14a48e8448d58e5cdae0ba905
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\ff\09\e7\4fc5109471fd53152f2b6a1b570c6e1ca879383edc3ce73445
Successfully built asciinema
Installing collected packages: asciinema
Successfully installed asciinema-2.0.1
PS C:\Users\user\Documents\GitHub\vagrant> asciinema rec
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\Scripts\asciinema.exe\__main__.py", line 4, in <module>
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\asciinema\__main__.py", line 9, in <module>
    from asciinema.commands.record import RecordCommand
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\asciinema\commands\record.py", line 6, in <module>
    import asciinema.asciicast as asciicast
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\asciinema\asciicast\__init__.py", line 11, in <module>
    from . import v2
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\asciinema\asciicast\v2.py", line 9, in <module>
    from asciinema.pty_recorder import PtyRecorder
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\asciinema\pty_recorder.py", line 3, in <module>
    import pty
  File "c:\users\user\appdata\local\programs\python\python39\lib\pty.py", line 12, in <module>
    import tty
  File "c:\users\user\appdata\local\programs\python\python39\lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'
PS C:\Users\user\Documents\GitHub\vagrant>

```

**Comment by sickill** [comment]
I've just pushed 2.1.0 to pypi.org.

**Comment by chenrui333** [comment]
@sickill looks like the tgz file was not pushed into pypi index.

**Comment by sickill** [comment]
Thanks @chenrui333 .

So thanks to @gpotter2 the release setup has been modernized, like this https://github.com/asciinema/asciinema/pull/422/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R22-R24 , but I'm not sure how to make it build/upload tgz. Any tips? I don't often release Python packages and I'm new to twine/wheel...

**Comment by harkabeeparolus** [comment]
Regarding [the installation instructions](https://asciinema.org/docs/installation), I propose that the Pip section is amended.

* I would suggest using [pipx](https://github.com/pypa/pipx/) as the primary way to install Python utilities. It's an official Python Packaging Authority project nowadays, and all the Python podcasts and news sources speak highly of it.

  You can install permanently with `pipx install asciinema`, or run a one-off with `pipx run asciinema play demo.cast`.

* I would also suggest *not* using sudo if you're using pip.

  The recommended incantation is `python3 -m pip install asciinema`. For ancient versions of pip, you need to specify `--user` as in `python3 -m pip install --user asciinema`, but recent pip versions default to the user's home directory when the python site-packages folder is not writable.

Rationale for both points above: See this blog post by Python steering council member and core developer Brett Cannon:
[Why you should use `python -m pip`](https://snarky.ca/why-you-should-use-python-m-pip/)

I suggest the following:

> ### Installing via Pip
> 
> asciinema is available on PyPI and can be installed with [pipx](https://github.com/pypa/pipx/) or pip (Python 3 required):
> 
> `pipx install asciinema`
> 
> Or with pip:
> 
> `python3 -m pip install asciinema`
> 
> This is the universal installation method for all operating systems, which always provides the latest version.

**Comment by sickill** [comment]
Thanks for the idea and great summary @harkabeeparolus. This sounds good to me. Would you care to open a PR with the proposed change?

**Comment by harkabeeparolus** [comment]
> Thanks for the idea and great summary @harkabeeparolus. This sounds good to me. Would you care to open a PR with the proposed change?

Sure, I can make a PR against your README.md file!

However, I can't find the repo for your official documentation: https://asciinema.org/docs/installation
...So I'm guessing an official team member would have to update that. 😄

**Comment by Wittionary** [comment]
I'm running into the same error as @aarek-eng , `ModuleNotFoundError: No module named 'fcntl'`.
It seems this module is not available for Windows users ([StackOverflow](https://stackoverflow.com/questions/45228395/error-no-module-named-fcntl)) because it's a unix/linux [system call](https://www.tutorialspoint.com/unix_system_calls/fcntl.htm) - unless I'm looking at the wrong thing.

I haven't taken a look at the asciinema source to see how large of an effort this would be, but is there the possibility of adding an alternate, Windows-supported `file control` library?

**Comment by itsmeboy0** [comment]
This works for windows: https://github.com/Watfaq/PowerSession

**Comment by sickill** [comment]
Please discuss Windows issues in separate issues (we do have a couple of them laying around). Thx!

**Comment by sickill** [comment]
I've just pushed 2.2.0 to pypi.org.

**Comment by zanchey** [comment]
I've updated my PPA. I don't use Ubuntu any more, and `pipx` looks like a better way to install in general, but the packages should still work. Debian doesn't have a good story for builds without a `setup.py`, so I added a patch that ships a minimal version.
