### ISSUE TITLE
OSError: out of pty devices

### ISSUE THREAD

**Issue by sbrl** [asciinema/asciinema#135]
I get a strange `OSError: out of pty devices` error when I use `asciinema rec` on my server.

Context: I ssh into my OVH VPS (Classic), which has 1 CPU Core, 1GB RAM, and a 10GB Hard Drive. I don't have control over my kernel due to the virtualisation technology used by OVH. (they use OpenVZ).

Here's my uname -a:
```
Linux starbeamrainbowlabs.com 2.6.32-042stab111.12 #1 SMP Thu Sep 17 11:38:20 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux
```

`/proc/sys/kernel/pty/max`:
```
4096
```

Here's the full error output:

```
~ Asciicast recording started.
~ Hit ctrl+d or type "exit" to finish.

Traceback (most recent call last):
  File "/usr/local/bin/asciinema", line 9, in <module>
    load_entry_point('asciinema==0.9.8', 'console_scripts', 'asciinema')()
  File "/usr/local/lib/python2.7/dist-packages/asciinema/__main__.py", line 7, in main
    get_command(sys.argv[1:], Config()).execute()
  File "/usr/local/lib/python2.7/dist-packages/asciinema/commands/record.py", line 23, in execute
    asciicast = self._record_asciicast()
  File "/usr/local/lib/python2.7/dist-packages/asciinema/commands/record.py", line 35, in _record_asciicast
    asciicast = self.recorder.record(self.cmd, self.title)
  File "/usr/local/lib/python2.7/dist-packages/asciinema/recorder.py", line 16, in record
    cmd or self.env['SHELL'])
  File "/usr/local/lib/python2.7/dist-packages/asciinema/timer.py", line 6, in timeit
    ret = callable(*args)
  File "/usr/local/lib/python2.7/dist-packages/asciinema/pty_recorder.py", line 88, in record_command
    pid, master_fd = pty.fork()
  File "/usr/lib/python2.7/pty.py", line 107, in fork
    master_fd, slave_fd = openpty()
  File "/usr/lib/python2.7/pty.py", line 29, in openpty
    master_fd, slave_name = _open_terminal()
  File "/usr/lib/python2.7/pty.py", line 70, in _open_terminal
    raise os.error, 'out of pty devices'
OSError: out of pty devices
```

**Comment by sickill** [comment]
I'm not sure why you're getting this error. FYI, this is almost 2 years old version of asciinema, I suggest you to try version >= 1.0.

**Comment by sbrl** [comment]
How can I install the latest version of asciinema? I'm on ubuntu server 15.10. Is there a ppa?

**Comment by sickill** [comment]
We have Ubuntu ppa, yes. See here https://asciinema.org/docs/installation

**Comment by sbrl** [comment]
Yep, that works. I found that I had an old version of asciinema lying around from who knows where that was overriding the newest version. I've deleted it now, and the new version works flawlessly :smiley:
