### ISSUE TITLE
fails after brew installation: ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by nictuku** [asciinema/asciinema#260]
``` 
$ brew install asciinema
Warning: asciinema 2.0.0 is already installed

$ asciinema 
Traceback (most recent call last):
  File "/usr/local/Cellar/asciinema/2.0.0/libexec/bin/asciinema", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'

Traceback (most recent call last):
  File "/usr/local/Cellar/asciinema/2.0.0/libexec/bin/asciinema", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

This isn't an asciinema problem but an issue with my installation - I'm probably lacking some important requirements. 

I am investigating this and will add notes for how to solve it.

**Comment by nictuku** [comment]
The fixes for me were:

```
 # to find and fix issues with my brew
$ brew doctor

$ brew install python3
Warning: python3 3.6.4_2 is already installed, it's just not linked.
You can use `brew link python3` to link this version.

$ brew link python3
Linking /usr/local/Cellar/python3/3.6.4_2... Error: Permission denied @ dir_s_mkdir - /usr/local/Frameworks

# It's possible that the linking would not be necessary if I skipped to the postinstall step.
$ sudo mkdir /usr/local/Frameworks
$ sudo chown $(whoami):admin /usr/local/Frameworks
$ brew link python3
Linking /usr/local/Cellar/python3/3.6.4_2... 1 symlinks created
```

At this point, it would still not work. So I ran:

```
$ brew postinstall python3
```

And then asciinema worked!

**Comment by VirtualFreak** [comment]
The brew post install python3 resolved it for me.  However, when trying to save a .cast locally (asciinema rec filename.cast), I am still getting some permissions issues.  However, using the post recording ctrl-c does save ir properly.

**Comment by sickill** [comment]
This is clearly packaging / homebrew issue. In the future please report these kind of issue to brew package maintainer(s) in brew formulas repository. Thanks!

**Comment by arunsathiya** [comment]
This helped me as well. Thank you!

**Comment by wanshaoyuan** [comment]
Thank you!

**Comment by lbrabus** [comment]
That works for me! Thank you!!

**Comment by aa1143** [comment]
the same error
thanks, it worked!

**Comment by qn7o** [comment]
That helped a lot, thanks mate.

**Comment by spchef** [comment]
Perfect ! 
This works for me , Thank you
