### ISSUE TITLE
Unable to run asciinema on python 3.10.4

### ISSUE THREAD

**Issue by Saeedprojects** [asciinema/asciinema#506]
It says in the asciinema v2.2.0 [release](https://github.com/asciinema/asciinema/releases) that offical support for python 3.10 was added, but I am getting this error when I try to run it asciinema in PowerShell command line. 

`Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\Scripts\asciinema.exe\__main__.py", line 4, in <module>
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\asciinema\__init__.py", line 12, in <module>
    from .recorder import record
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\asciinema\recorder.py", line 5, in <module>
    from . import pty_ as pty  # avoid collisions with standard library `pty`
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\asciinema\pty_.py", line 3, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'`

**Comment by Saeedprojects** [comment]
> same

Decided to stick to 3.6 version for the recording part. Ref this if still stuck https://www.reddit.com/r/learnpython/comments/v6nu2d/what_is_the_best_way_to_record_and_share_code_as/?utm_source=share&utm_medium=ios_app&utm_name=iossmf
